/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package volume;

import javax.swing.JOptionPane;

/**
 *
 * @author asus
 */
public class Frame1 extends javax.swing.JFrame {

    /**
     * Creates new form Frame1
     */
    public Frame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Kubus = new javax.swing.JTextField();
        btnKubus = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        Bola = new javax.swing.JTextField();
        BtnBola = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Panjang = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Lebar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Tinggi = new javax.swing.JTextField();
        btnBalok = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Harrington", 1, 18)); // NOI18N
        jLabel2.setText("Program Pencari Volume Bangun Ruang");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 20, 410, 22);

        jPanel5.setLayout(null);

        jLabel6.setText("Masukkan Panjang Sisi       :");
        jPanel5.add(jLabel6);
        jLabel6.setBounds(41, 46, 160, 14);
        jPanel5.add(Kubus);
        Kubus.setBounds(205, 46, 107, 30);

        btnKubus.setText("VOLUME");
        btnKubus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKubusActionPerformed(evt);
            }
        });
        jPanel5.add(btnKubus);
        btnKubus.setBounds(219, 93, 110, 23);

        jLabel12.setText("cm");
        jPanel5.add(jLabel12);
        jLabel12.setBounds(316, 49, 40, 14);

        jTabbedPane2.addTab("Kubus", jPanel5);

        jPanel6.setLayout(null);

        jLabel7.setText("Masukkan Panjang Jari-Jari        :");
        jPanel6.add(jLabel7);
        jLabel7.setBounds(46, 51, 190, 14);
        jPanel6.add(Bola);
        Bola.setBounds(251, 48, 116, 30);

        BtnBola.setText("VOLUME");
        BtnBola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBolaActionPerformed(evt);
            }
        });
        jPanel6.add(BtnBola);
        BtnBola.setBounds(165, 100, 110, 23);

        jLabel8.setText("cm");
        jPanel6.add(jLabel8);
        jLabel8.setBounds(371, 51, 40, 14);

        jTabbedPane2.addTab("Bola", jPanel6);

        jPanel4.setLayout(null);

        jLabel3.setText("Masukkan Panjang    :");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(45, 36, 120, 14);
        jPanel4.add(Panjang);
        Panjang.setBounds(187, 23, 172, 30);

        jLabel4.setText("Masukkan Lebar       :");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(48, 74, 120, 14);
        jPanel4.add(Lebar);
        Lebar.setBounds(187, 61, 172, 30);

        jLabel5.setText("Masukkan Tinggi        :");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(44, 112, 130, 14);
        jPanel4.add(Tinggi);
        Tinggi.setBounds(187, 99, 172, 30);

        btnBalok.setText("Hitung");
        btnBalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBalokActionPerformed(evt);
            }
        });
        jPanel4.add(btnBalok);
        btnBalok.setBounds(158, 182, 81, 23);

        jLabel9.setText("cm");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(363, 36, 31, 14);

        jLabel10.setText("cm");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(363, 74, 30, 14);

        jLabel11.setText("cm");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(363, 112, 40, 14);

        jTabbedPane2.addTab("Balok", jPanel4);

        getContentPane().add(jTabbedPane2);
        jTabbedPane2.setBounds(0, 60, 490, 270);

        setBounds(0, 0, 502, 369);
    }// </editor-fold>//GEN-END:initComponents

    private void btnKubusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKubusActionPerformed
        // TODO add your handling code here:
        int sisi;
        sisi = Integer.parseInt(Kubus.getText());
        int hasil = sisi*sisi*sisi;

        try{
            JOptionPane.showMessageDialog(null, "Volume Kubus Adalah :"+hasil,"Volume",
                JOptionPane.INFORMATION_MESSAGE);
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error:"+e,"Gagal",
                JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnKubusActionPerformed

    private void BtnBolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBolaActionPerformed
        // TODO add your handling code here:
        float jari;
        jari = Integer.parseInt(Bola.getText());
        float hasil1 = (float) (4/3*3.14*jari*jari*jari);

         try{
            JOptionPane.showMessageDialog(null, "Volume Bola Adalah :"+hasil1,"Volume",
                        JOptionPane.INFORMATION_MESSAGE);
            }
            catch (Exception e){
                JOptionPane.showMessageDialog(null, "Error:"+e,"Gagal",
                        JOptionPane.INFORMATION_MESSAGE);
            }    

    }//GEN-LAST:event_BtnBolaActionPerformed

    private void btnBalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBalokActionPerformed
        // TODO add your handling code here:
        int panjang, lebar, tinggi;
        panjang = Integer.parseInt(Panjang.getText());
        lebar   = Integer.parseInt(Lebar.getText());
        tinggi  = Integer.parseInt(Tinggi.getText());
        int hasil = panjang*lebar*tinggi;
        try{
            JOptionPane.showMessageDialog(null, "Volume Balok Adalah :"+hasil,"Volume",
                JOptionPane.INFORMATION_MESSAGE);
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error:"+e,"Gagal",
                JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnBalokActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Bola;
    private javax.swing.JButton BtnBola;
    private javax.swing.JTextField Kubus;
    private javax.swing.JTextField Lebar;
    private javax.swing.JTextField Panjang;
    private javax.swing.JTextField Tinggi;
    private javax.swing.JButton btnBalok;
    private javax.swing.JButton btnKubus;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane2;
    // End of variables declaration//GEN-END:variables
}
